#!/usr/bin/env python

import rospy
from geometry_msgs.msg import TwistStamped, Twist
rospy.init_node('Velocity_odometry', anonymous=True)
class OdomConvert():
    def __init__(self):
        rospy.Subscriber("/wheel_odom", TwistStamped, self.getVelocity)
        self.pubVelocity = rospy.Publisher('/velocity_odom', Twist,queue_size = 1)
        while not rospy.is_shutdown():
            pass
    def getVelocity(self, data):
        linear = data.twist.linear.x
        angular = data.twist.angular.z
        
        left = linear - 0.91*angular
        right = linear + 0.91*angular
        
        wiadomosc = Twist()
        wiadomosc.linear.x = left
        wiadomosc.linear.y = right
        self.pubVelocity.publish(wiadomosc)
        
if __name__ == '__main__':
    OdomConvert()
